### ISSUE TITLE
Replication metrics

### ISSUE THREAD

**Issue by Rouiy** [MathLee/GeleNet#1]
Hello, your work has helped me a lot, but when I reproduce your code it doesn't meet the metrics in your paper, is there any further change to the project but not updated?

**Comment by MathLee** [comment]
We provide trained parameters that you can use directly. Inconsistent results are influenced by various factors, such as randomly initialized parameters. You can train more times to choose a better result.

**Comment by Rouiy** [comment]
Ok, thanks for the reply
